name: caddsv_score_r
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::r-base=4.5.2
- conda-forge::r-data.table=1.17.8
- conda-forge::r-dplyr=1.1.4
- conda-forge::r-optparse=1.7.5
- conda-forge::r-randomforest=4.7_1.2
- conda-forge::r-ranger=0.17.0
- conda-forge::r-readr=2.1.6
- conda-forge::r-stringr=1.6.0